version: "3.9"
services:
  postgres_db:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  migrations:
    image: node
    command: npm run migrate
    depends_on:
      - postgres_db
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST: "postgres_db"
  nodejs_backend:
    build: ./
    image: node
    ports:
      - "3000:3000"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST: "postgres_db"
    depends_on:
      - postgres_db
      - migrations